### ISSUE TITLE
The form does not shrink/grow with the browser window

### ISSUE THREAD

**Issue by wizardshill** [vyadh/teamcity-deployment-dashboard#11]
The form size seems to be fixed, when I increase the size of the browser windows the form or report stays the same size.

Long project names take-up multiple lines.

**Comment by vyadh** [comment]
Interesting. Is it possible to add a screenshot?

The dashboard is designed to grow/shrink to a size that "looks right" but not to 100% to avoid everything looking too spaced out.

However, if you've got long project names maybe this doesn't quite work as intended, and the text wraps too early rather than increasing the grid width. One thing I did want to avoid is having project names that make the width so wide it meant you ended up with a horizontal scrollbar.

Since there are no width limits set on the columns, I'm not sure what's going on here. I guess I'll have to see if I can avoid wrapping the project name up to the screen width, but then allow wrapping... Sounds like a bit of a challenge! Bit of investigation needed I think.

**Comment by wizardshill** [comment]
![Screen Shot 2019-07-12 at 3 36 09 PM](https://user-images.githubusercontent.com/9683200/61161878-d0796600-a4ba-11e9-922e-045915e1e129.png)

**Comment by vyadh** [comment]
Thanks, that's helpful.

I found the problem. I have a fix for the next release (v1.7), however I'm now struggling to get the table to stretch a bit when there is little content as it used to without having to fill the whole width (need to brush up on my CSS skills clearly!).

I'll see if I can resolve this before cutting the new version.

**Comment by vyadh** [comment]
Okay I solved the other problem I was having - a bit of CSS grid rather than HTML tables was all I needed. Have a try of the new version and see if it fixes your problem.

**Comment by wizardshill** [comment]
looks good, thanks
