### ISSUE TITLE
Production env in different project

### ISSUE THREAD

**Issue by nekhozhin** [vyadh/teamcity-deployment-dashboard#12]
Hey!
First of all many thanks for this great project!
We are using production env in different project because of security reasons. Any chance you can add possibilities to take environments from different projects? For example by project ID + env.param.

**Comment by vyadh** [comment]
Thanks. Glad you're finding it useful.

I think you should actually already be able to do that (in fact, I do something similar). If I understand what you need correctly, what can do is change the plugin config at a higher level that holds both projects and specify the "project property" (rather than leaving it blank). Then update both projects with a property with the same value (or just once if they are part of a common project for that system if that is more useful). E.g. both projects specifying "Moon Service". The plugin with then treat deployments from both project as the same system.

Less sure what you mean about environments... What you can do is specify, e.g. "Development,Production" at the higher level configuration and have your two separate projects supply the actual deployment builds for each.

Let me know if that works, or if you meant something different.

**Comment by nekhozhin** [comment]
Yes, it is. It works as you described.
Thanks!

**Comment by vyadh** [comment]
Great. Thanks for letting me know.
