### ISSUE TITLE
More generic dashboard

### ISSUE THREAD

**Issue by michaeloa** [vyadh/teamcity-deployment-dashboard#24]
Two things that I would like to see:
- Making this applicable to all builds, not just Build configurations of type deployments. Is there any reason it _has_ to be deployment build configs?
- Being able to switch off the highlighting of the latest "version".

My use case: We have a "project" that collects higher-level test suites running in a multitude of environments. It would be great to have a dashboard that displays the current status of each of those. This pretty much permits us to do that, though the two features above are "annoyances" for that use-case.

Is this something you might consider fixing, accept a PR for, or would it be better to fork the dashboard for our own needs?

**Comment by vyadh** [comment]
Understandable comments... On the first question, just because it suits my particular purposes as we have a lot of builds and few deployments. I'd be happy to get a PR for these changes, but tbh it would be a bit to make this configurable. However, to just make the above changes for your use case, I think it should be pretty easy.

So I recommend the following:
1. Fork the project
2. Open the DeployFinder class and remove the ".filter { isDeployment(it) }" call (and update/disable any tests as needed)
3. Open the Deployment.css file and change the "#deploys .status-older" selector to "opacity: 1.0"
4. Rebuild

I haven't tested this, but hopefully it's as easy as that.

Building the plugin wasn't particularly easy/obvious though, so just today I've added a Docker build and build.sh wrapper script so it should now be trivial (hopefully) for you to do above.

If there is more demand for these features I'll consider adding above into the main codebase, but I don't get a lot of time to work on this so I'll close this for now, but feel free to comment or ask for help on above.

I do have a few minor features/fixes to do in the next few weeks so you might want to keep an eye out in case these are useful for you.

**Comment by michaeloa** [comment]
NP. Thanks for the quick response.
